sensors:
 - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
   point_cloud_topic: /move_group/camera/depth_registered/points
   max_range: 1.5
   padding_offset: 0
   padding_scale: 2.0
   filtered_cloud_topic: filtered_cloud
   point_subsample: 1
   frame_subsample: 10
